#!/bin/sh

if [ $# -lt 1 ]; then
    echo "Usage: $0 <presentation> [stylesheet]"
    exit 1
fi

presentation="$1"
if [ $# -ge 2 ] && [ -f "$2" ]; then
    stylesheet="$(cat "$2")"
else
    stylesheet='
body {
    font-family: sans-serif;
    margin: 0;
    line-height: 1.6;
    font-size: 46px;
    color: #6e655e;
    background-color: #fefbec;
}

.content-body {
    margin: 40px auto;
    max-width: 800px;
    color: #6e655e;
    padding: 0 0.55em;
}

h1, h2, h3 {
    line-height: 1.2;
}

hr {
    color: #e5e2d3;
    background-color: #e5e2d3;
    border: none;
    height: 2px;
}

a {
    color: #1fad83;
}

a:visited {
    color: #6684e1;
}

.header-links {
    max-width: 750px;
    margin: 10px auto;
    padding: 0 0.55em;
}

.header-links a {
    color: #6e655e;
    text-decoration: none;
    font-size: 1.2em;
    font-weight: bold;
}

.header-links a:hover {
    text-decoration: underline
}

.footer-links {
    max-width: 750px;
    margin: 20px auto;
    padding-bottom: 18px;
}

.footer-links a {
    float: left;
    color: #6e655e;
    text-decoration: none;
    font-size: 0.8em;
    font-weight: bold;
    line-height: 1;
    padding: 0em 0.2em;
    border-right: 0.12em solid #6e655e;
}

.footer-links a:hover {
    text-decoration: underline;
}

.footer-links a:last-child {
    border-right: none;
}
            h1, h2, h3 {
    border-bottom: 0.08em solid #e5e2d3;
}

.img-right {
    float: right;
    margin-left: 0.5em;
}

.img-left {
    float: left;
    margin-right: 0.5em;
}

.table-wrapper {
    overflow: auto;
}

table {
    width: 100%;
    font-size: 1em;
    outline: none;
    border-spacing: 0px;
}

tr.odd {
    background-color: #eee8d5;
}

th {
    color: #586e75;
}

th, td {
    padding-left: 0.5em;
    padding-right: 0.5em;
    padding-top: 0.3em;
    padding-bottom: 0.3em;
}

div.small {
    width: 60%;
}

div.medium {
    width: 75%;
}

div.large {
    width: 100%;
}

div.font_normal table {
    font-size: 1em;
}

pre {
    font-family: monospace;
    line-height: 1.2;
    overflow-x: auto;
    background-color: #eee8d5;
    padding: 0.2em;
    border-radius: 3px;
}

code {
    font-size: 0.85em;
    font-family: monospace;
}

p code {
    background-color: #eee8d5;
    padding: 0em 0.2em;
    border-radius: 3px;
}
'
fi
slides="$presentation-slides"
slide_template='
<html>
    <head>
        <style>
            '"$stylesheet"'
        </style>
    </head>
    <body>
        <div class="content-body">
        <h1>$title</h1>
        $body
        </div>
    </body>
    <script>
        function nextSlide() {
            window.location.href = "$next_slide";
        }
        function prevSlide() {
            window.location.href = "$prev_slide";
        }
        var actions = {
            "Enter": nextSlide,
            "ArrowRight": nextSlide,
            "l": nextSlide,
            "ArrowLeft": prevSlide,
            "h": prevSlide
        };
        document.addEventListener("keydown", function(evt) {
            var act = actions[evt.key];
            if (act) {
                act();
            }
        });
    </script>
</html>
'

mkdir -p "$slides"

awk \
    -v slide_dir="$slides" \
    -v slide_template="$slide_template" \
    < "$presentation" \
'
    BEGIN {
        slide_number = 1
    }
    
    /^#/ {
        gsub(/^# */, "")
        title = $0
    }

    /^-/ {
        gsub(/^- */, "")
        bullets = bullets $0 "\n"
    }

    function getSlideFileRelative(n) {
        return "slide-" n ".html"
    }

    function getSlideFileAbsolute(n) {
        return slide_dir "/" getSlideFileRelative(n)
    }

    function finishSlide(is_last_slide, i, list_items, body, slide_html) {
        slide_file = getSlideFileAbsolute(slide_number)
        if (slide_number == 1) {
            prev_slide = getSlideFileRelative(slide_number)
        } else {
            prev_slide = getSlideFileRelative(slide_number - 1)
        }
        if (is_last_slide) {
            next_slide = getSlideFileRelative(slide_number)
        } else {
            next_slide = getSlideFileRelative(slide_number + 1)
        }
        slide_html = slide_template

        body = "<ul>\n"
        split(bullets, list_items, /\n/)
        for (i in list_items) {
            if (list_items[i] != "") {
                body = body "<li>" list_items[i] "</li>\n"
            }
        }
        body = body "</ul>\n"
        
        gsub(/\$title/, title, slide_html)
        gsub(/\$body/, body, slide_html)
        gsub(/\$next_slide/, next_slide, slide_html)
        gsub(/\$prev_slide/, prev_slide, slide_html)

        print slide_html > slide_file
        close(slide_file)

        slide_number++
        title = ""
        bullets = ""

        print "Wrote slide " slide_file
    }

    /^ *$/ {
        finishSlide()
    }

    END {
        if (title != "" || bullets != "") {
            finishSlide()
        }
        title = "End"
        bullets = ""
        finishSlide(1)
    }
'
